bluemix/token_refresher/fakes/fake_token_refresher.go, bluemix/token_refresher/token_refresher.go, bluemix/token_refresher/token_refresher_test.go, plugin/fakes/fake_plugin_context.go, plugin/plugin.go, plugin/plugin_context.go
…token in config after refresh.
=> Rename PluginContext's TokenRefresh() to RefreshAccessToken

utils/Readme.md, utils/new-command.sh, utils/project.properties, utils/setup-project.sh
https://github.com/IBM-Bluemix/bluemix-cli-sdk/issues/23
=> initial check-in of utils to create project and command

plugin/models/organization.go, plugin/models/space.go, plugin/plugin.go, plugin/plugin_context.go, plugin/pluginfakes/fake_plugin_context.go, plugin_examples/list_plugin/commands/list.go, plugin_examples/list_plugin/commands/list_test.go
1. Remove package plugin/models
2. Add Account() in plugin context to provide account name.
=> Provide account name in plugin context

docs/plugin_developer_guide.md
https://github.com/IBM-Bluemix/bluemix-cli-sdk/issues/38
=> Add documentation for sub-namespaces

bluemix/terminal/color.go
https://github.com/IBM-Bluemix/bluemix-cli-sdk/issues/53
=> Fix isTerminal issue

bluemix/terminal/color.go
correct ANSI color code according to https://en.wikipedia.org/wiki/ANSI_escape_code
=> Fix header color not displayed in windows issue:

utils/setup-project.sh
https://github.com/IBM-Bluemix/bluemix-cli-sdk/issues/80
=> Fix wrong language locale for i18n "ja_JA", replace it with "ja_JP"

plugin/plugin.go
https://github.com/IBM-Cloud/ibm-cloud-cli-sdk/issues/93
=> provide option to hide plugin commands and flags

bluemix/trace/trace.go
* hide X-Auth* header
* fix token in request body not hidden issue
=> update trace logger's sanitize regular rexpression

bluemix/authentication/errors.go, bluemix/authentication/iam/iam.go
=> feat(sdk): add new error for refresh token expiry

bluemix/authentication/iam/iam.go, common/file_helpers/file.go, common/file_helpers/gzip.go, plugin_examples/list_plugin/plugin.go
to check gosec issues run the following commands:
```
gosec ./...
```
=> resolve gosec issues

bluemix/env.go, bluemix/terminal/table.go, bluemix/terminal/table_test.go, bluemix/terminal/ui.go
1. add quite mode to terminal.UI
2. add environment variable `IBMCLOUD_QUIET` which is used to pass quiet mode from base CLI to plugin
resolve #201
=> feat(ui): add quiet mode to UI

bluemix/configuration/core_config/bx_config.go, bluemix/configuration/core_config/repository.go
1. Deprecate old core config property `UsageStatsDisabled`
2. Add new property `UsageStatsEnabled`
resolve #206
=> feat(SDK): add Core Config `UsageStatsEnabled`

.secrets.baseline
In order to integrate https://github.com/IBM/detect-secrets
=> add detect-secrets baseline

bluemix/trace/trace.go, bluemix/trace/trace_test.go
1. add unit tests
2. improve comments
=> test(api): add unit tests to `bluemix/trace`

docs/plugin_developer_guide.md
=> docs(guide): section for targeting region/resource group

.secrets.baseline, common/rest/client.go, common/rest/helpers/client_helpers_test.go
=> chore: add unit tests for IsJSONStream

.secrets.baseline, .travis.yml, bluemix/authentication/iam/iam.go, common/downloader/file_downloader.go, common/file_helpers/file.go, common/file_helpers/gzip.go
Also enables gosec in the travis build.
=> Promote gosec changes

common/file_helpers/file.go, common/file_helpers/gzip.go
Promoting the fixes in `dev` to `master`.
=> fix: clean path in file_helpers

.travis.yml, bluemix/authentication/iam/iam.go, docs/plugin_developer_guide.md, plugin_examples/list_plugin/plugin.go
This PR promotes the VPC VSI developer doc changes, along with some nosec and build related changes from the dev branch.
=> Promote VPC VSI doc updates

plugin_examples/list_plugin/plugin.go
* chore: provide gosec comment for plugin_example
* chore: correct gosec comment
Co-authored-by: philip-schmidt <philip.schmidt@ibm.com>
=> chore: provide gosec comment for plugin_example (#313)

.secrets.baseline, bluemix/version.go, docs/plugin_developer_guide.md
=> docs: Added how to handle empty object using --output json

.secrets.baseline, bluemix/version.go, docs/plugin_developer_guide.md
=> chore: Bump version to 0.11.0

bluemix/version.go
=> chore: Bump for release 1.0.0

bluemix/authentication/iam/iam.go, bluemix/authentication/iam/iam_test.go, bluemix/configuration/core_config/bx_config.go, bluemix/configuration/core_config/bx_config_test.go, bluemix/configuration/core_config/repository.go, bluemix/version.go, docs/plugin_developer_guide.md
See PR #335 for more information
=> feat: Cherry pick session refresh feature

bluemix/terminal/table.go, bluemix/terminal/table_test.go
=> Fix trailing spaces on table rows

.travis.yml
This PR will update to the latest version of nancy
=> build(travis): Updated nancy to latest version

go.mod, go.sum
Bump version of golang.org/x/text
=> build(deps): Update golang.org/x/text

.gitignore, bluemix/configuration/core_config/bx_config.go, bluemix/configuration/core_config/cf_config.go, bluemix/configuration/persistor.go, go.mod, go.sum
=> Fix: Improvement to Concurrency Tolerance

bluemix/version.go
=> chore: bump to 1.1.2

bluemix/version.go
=> chore: bumped version to v1.6.0

bluemix/configuration/core_config/bx_config.go, bluemix/configuration/core_config/bx_config_test.go, bluemix/configuration/core_config/repository.go, bluemix/version.go
Cherry-picked commits from dev for new release 1.7.0.
=> Changes to create version 1.7.0

bluemix/terminal/table.go, bluemix/terminal/table_test.go, plugin/pluginfakes/fake_plugin_context.go
The purpose of this PR is to add the missing mock for `MCPEnabled`. Also, cherry picked the commit from https://github.com/IBM-Cloud/ibm-cloud-cli-sdk/pull/455 in order for the changes to not be lost in `dev`
=> test: updated PluginContext mock
