IBM-Cloud/ibm-cloud-cli-sdk

- docs/plugin_developer_guide.md
We need to define some rules regarding recommended command syntax design, so that the styles of different plugin command syntax are consistent.
> add a section regarding command syntax guide

- bluemix/authentication/authentication_iam.go
- bluemix/configuration/core_config/iam_token.go
- plugin/plugin_context.go
1. Get IAM token with response type cloud_iam only
2a. Refresh IAM token for acccount with response type cloud_iam and uaa (now we also have a UAA token)
2b If not selecting an account, simply get a uaa token with grant type "derive"
> Supoprt optimizing the authentication flow:

- docs/plugin_developer_guide.md
Changes include:
- plugin —> plug-in
- some wording to increase clarity
- some formatting for steps
- reword some examples
- add guidance for putting command name at end of sentences in output
messages
> Changes to align guidance with IBM Style

- bluemix/configuration/config_helpers/helpers.go
- bluemix/configuration/config_helpers/helpers_test.go
- bluemix/configuration/core_config/repositroy.go
- common/file_helpers/file.go
* change name from '.bluemix' to '.ibmcloud'
* if new config dir exist, load config from the new config dir,
otherwise still load from the old config dir
* file helper should copy file mode when copying file
> prepare to change config dir:

- bluemix/crn/crn.go
`cf` is the service name for public Cloudfoundry, and `cfaas` is the service name for CFEE Cloudfoundry.
> feat(crn): add new service name values `cf` and `cfaas`

- bluemix/configuration/core_config/bx_config.go
- bluemix/configuration/core_config/repository.go
Since there are other types of logged-in *users*, email is not capable of being a human  readable ID
to display on console. This commit will add a new method `UserDisplayText()` to core config, to support more types of logged in users.
> feat(sdk): add `UserDisplayText()` to ibm cloud core config

- bluemix/http/transport.go
- bluemix/http/transport_test.go
octet stream could be very large, and it's hard for users to read
from screen. So we should skip dumping its contents for:
- avoid out of memory error, and improve memory footprint
- enhance the readability of trace output
This commit will:
1. check the `content-type` and skip dumping response if it is
`octet-stream` types
2. update unit test
resolve #194
> fix(trace): skip dumping octet stream response

- bluemix/configuration/core_config/bx_config.go
- bluemix/configuration/core_config/bx_config_test.go
- bluemix/configuration/core_config/repository.go
1. add property `UsageStatsLastUpdate` in `bxConfig`
2. add reader `UsageStatsLastUpdate` in `Repository`, which can be used to decided last time user has changed `UsageStatsEnabled`
3. add reader `UsageStatsAllowed` in `Repository`, which indicates whether it's allowed to collect usage statistics. Usage statistics is allowed only when `UsageStatsEnabled` is true, and `UsageStatsLastUpdate` is not zero.
4. update `SetUsageStatsEnabled` in `Repository`, now if this writer is invoked, the `UsageStatsLastUpdate` will be updated as well.
5. add unit tests
resolve #206
> feat(config): add `UsageStatsLastUpdate`

- bluemix/configuration/core_config/cf_config.go
- bluemix/configuration/core_config/cf_config_test.go
- bluemix/configuration/core_config/repository.go
* sync latest config data from upstream cf cli project
* remove `LoggregatorEndpoint` property and corresponding codes
* add `UAAGrantType` property, but not setter/getter
* remove compatibility check and purge logic, we should delegate it
to CF CLI
* set default config version to `4` if not set
* add unit test
resolve #218
> feat(cf): support load cf config v4 or later

- bluemix/configuration/core_config/cf_config.go
- bluemix/configuration/core_config/repository.go
1. add readers in `CFConfig` interface for properties returned in `cf
config` command
1.1 AsyncTimeout
1.2 ColorEnabled
1.3 Locale
1.4 Trace
2. implement reader of `AsyncTimeout` in CFConfigData
> feat(cf): add readers of cf config properties

- common/rest/client.go
- common/rest/client_test.go
Add a DoWithContext to allow cancellable calls from rest client. Comment changes echo terminology from the go docs https://golang.org/pkg/net/http/#NewRequest
> Add DoWithContext to rest client

- testhelpers/terminal/test_ui.go
Only "OK" and "Failed" are output by this testhelper, but they should be colored if ther terminal type is fit for colorization or if color package has been forced to colorize by the unit test.
Fixes #214
> Allow testhelpers/terminal.FakeIU to color output

- docs/plugin_developer_guide.md
This PR adds a section to the end of the CLI Developer Guide on the deprecation policy for CLI Plugins.  In a nutshell, the policy is to follow semantic versioning rules for CLI plugins and to ensure support for plugins for at least one year, consistent with the policy for SDKs.
I also fixed a few minor issues with head levels and cleaned up some trailing whitespace.
> doc: add section to the developers guide on deprecation policy

- bluemix/terminal/prompt.go
- common/file_helpers/file.go
- common/rest/request.go
- plugin/plugin_shim.go
- plugin_examples/list_plugin/plugin.go
```
go test ./...
ok      github.com/IBM-Cloud/ibm-cloud-cli-sdk/bluemix  (cached)
?       github.com/IBM-Cloud/ibm-cloud-cli-sdk/bluemix/authentication   [no test files]
?       github.com/IBM-Cloud/ibm-cloud-cli-sdk/bluemix/authentication/iam       [no test files]
?       github.com/IBM-Cloud/ibm-cloud-cli-sdk/bluemix/authentication/uaa       [no test files]
?       github.com/IBM-Cloud/ibm-cloud-cli-sdk/bluemix/configuration    [no test files]
plugin_examples/context.go:14:6: main redeclared in this block
previous declaration at plugin_examples/auto_complete_delegation.go:12:6
plugin_examples/hello.go:11:6: main redeclared in this block
previous declaration at plugin_examples/context.go:14:6
plugin_examples/namespace.go:11:6: main redeclared in this block
previous declaration at …
```
> fix: low asoc findings

- .gitignore
- common/rest/client.go
- common/rest/client_test.go
- common/rest/helpers/client_helpers.go
- common/rest/helpers/client_helpers_test.go
- vendor/vendor.json
This PR adds support for decoding yaml response bodies in the rest client. When a response body is received, now the client will attempt to identify the bytes as either a json or yaml response body. In the case of the body being in yaml format, the [go-yaml](https://github.com/go-yaml/yaml/tree/v2.4.0) decoder is used to unmarshal the response.
The go-yaml package was updated to v2.4.0
ref: https://github.ibm.com/Bluemix/bluemix-cli/issues/3481
> feat: add support for parsing yaml response bodies **DO NOT MERGE**

- common/file_helpers/file.go
This PR updates the `CopyFile` method to use Go's [Chmod](https://golang.org/pkg/os/#Chmod) ``os`` function since it's compatible across different operating systems. This bug was exposed through the addition of error handling: https://github.com/IBM-Cloud/ibm-cloud-cli-sdk/commit/f322ddbdca7b23ff9bb13f29f4c5fd6ed009fd93#diff-ed4c5da476b144b27ead262d23553593edc97ab9030fdca07a62ec5166408447R56
Fixes 
```
Installing binary...
FAILED
Unable to copy the plug-in binary: chmod C:\Users\Administrator\.bluemix\plugins\container-registry\container-registry.exe: not supported by windows
```
on windows.
> use os.Chmod instead of file.Chmod for Windows compatibility

- bluemix/authentication/iam/iam.go
False positive found by `gosec` during vulnerability scan: https://github.ibm.com/arf/security-and-compliance/blob/master/asoc/reports/20210919160307/cli-squad_ibm-cloud-cli-sdk.html
The keyword "token" is causing the scan to think a sensitive value is being revealed
> chore: ignore gosec false positive

- .secrets.baseline
- bluemix/authentication/iam/iam.go
- bluemix/authentication/iam/iam_test.go
This PR updates the iam authenticator to include a new token request method `CRTokenRequestWithCRN`. This allows building an IAM token request with the `cr_token` grant type and a new optional form parameter `profile_crn` to specify a trusted profile CRN.
> feat: add support for specifying 'profile_crn' param in CRTokenRequest

- CODEOWNERS
adding code owners as doc'd in https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> build: define code owners file

- bluemix/authentication/errors.go
- bluemix/authentication/iam/iam.go
- bluemix/authentication/iam/iam_test.go
- i18n/resources/de_DE.all.json
- i18n/resources/en_US.all.json
- i18n/resources/es_ES.all.json
- i18n/resources/fr_FR.all.json
- i18n/resources/it_IT.all.json
- i18n/resources/ja_JP.all.json
- i18n/resources/ko_KR.all.json
- i18n/resources/pt_BR.all.json
- i18n/resources/zh_Hans.all.json
- i18n/resources/zh_Hant.all.json
- resources/i18n_resources.go
Currently, the sdk does not parse errors where the session becomes inactive when checking the token. This PR will process the session inactive error by checking the error code similar to the other errors.
**Callout: Changes replaces the literal error codes to constants to improve readability and reuse. This change does not effect existing behavior.**
1. Run the unit tests under the `bluemix` module and verify that the new tests in `iam_test.go` file pass
2. Run all unit tests and verify that all tests pass (regression)
> fix: Handled session inactive error when getting token

- common/rest/client.go
- common/rest/client_test.go
Currently, the rest client will return an error object if there is an empty response body. This can be a problem if the response is a 204 No Content where there may not be a response body. This PR will allow the client to return the response without an error when the status is 204
1. Run new tests in the `comment/rest` package.
2. Verify that the tests pass
> fix(common): Allowed empty response body for 204

- .secrets.baseline
- .travis.yml
- bluemix/authentication/iam/iam.go
- common/downloader/file_downloader.go
- common/file_helpers/file.go
- common/file_helpers/gzip.go
This PR adds a gosec scan to the travis build and addresses a few false positives.
The workaround for the file closer explained in https://github.com/securego/gosec/issues/512 seems to still cause a gosec failure in the latest version of gosec. The issue https://github.com/securego/gosec/issues/714 has been opened against the gosec team to provide a fix. For now, we will add a nosec flag until a proposed fix, or workaround is out.
> fix(gosec): address false positives

- common/downloader/file_downloader.go
- common/file_helpers/file.go
- common/file_helpers/gzip.go
securego/gosec#714 was fixed in the latest version of gosec (v2.9.3). We no longer need these flags.
> fix(gosec): remove 'nosec G307'

- .secrets.baseline
- vendor/vendor.json
This PR addresses [CVE-2021-43565 ](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2021-43565) and  [CVE-2020-29652](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2020-29652). The `golang.org/x/crypto` package was upgraded to `v0.0.0-20201216223049-8b5274cf687f` which contains both fixes.
Full diff: https://github.com/golang/crypto/compare/85f98707c97e11569271e4d9b3d397e079c4f4d0...5770296d904e
These CVEs seems to be unique to the `golang.org/x/crypto` package and not the `golang.org/x/crypto/ssh/terminal` package which is all the SDK uses. So the blast radius of this is smaller than what the full diff shows.
> fix: upgrade 'golang.org/x/crypto' package to address CVE-2020-29652 and CVE-2021-43565

- bluemix/terminal/table.go
- bluemix/terminal/table_test.go
- common/file_helpers/file.go
- common/file_helpers/gzip.go
I use this table library a lot in the `ibmcloud sl` plugin, and it would be nice to have a way to simply print the table as a JSON string. Currently my only option is to print the raw data that went into the table originally, which might not match up exactly with what I want to show the user.
My approach here was to just render the table as an array, each row being an object with each property matching a column in the table.
For example
```go
testTable := NewTable(&buf, []string{"test1", "test2"})
testTable.Add("row1-col1", "row1-col2")
testTable.Add("row2-col1", "row2-col2")
testTable.PrintJson()
```
would render something like this:
```json
[
{
"test1": "row1-col1",
"test2": "row1-col2"
},
{
"test1": "row2-col1",
"test2": "row2-col2"
}
]
```
> Adds PrintJson to bluemix/terminal/table

- plugin_examples/list_plugin/plugin.go
With updated gosec, the comment has to be relocated to above struct
> chore: update gosec comment in example

- .secrets.baseline
- docs/plugin_developer_guide.md
The purpose of this PR is to give guidance to plugin developers on the expected behavior for an empty object response when using the `--output json` option flag. If no object is returned we should expected the plugin to return an error
> docs: Added how to handle empty object using --output json

- docs/plugin_developer_guide.md
This PR will add a new sub section under **Utility for Unit Testing** section. This new section will explain how to use use the test doubles provided by the fake interfaces generated by `counterfeiter`. There are also examples on how to use some of the widely used test double methods
> docs: Added how to use test doubles in guide

- plugin/plugin.go
- plugin_examples/list_plugin/plugin.go
This PR will add a boolean metadata flag `IsCobraPlugin` to determine if a plugin created using the cobra framework. This metadata flag will fix some of the computed metadata used in generating the usage help text between plugins created by urfave and cobra.
> feat(plugin): Added meta flag to detect if cobra plugin

- bluemix/authentication/iam/iam.go
- bluemix/authentication/iam/iam_test.go
- bluemix/configuration/core_config/bx_config.go
- bluemix/configuration/core_config/bx_config_test.go
- bluemix/configuration/core_config/repository.go
- docs/plugin_developer_guide.md
This PR will add a new config property called `LastSessionUpdateTime` which will keep track of the last time the session was updated. The config property will be set to the current timestamp. The property will be set on login, refresh token, and after each CLI command has been executed
Also, a new method called `RefreshSession` is added to allow refreshing the current session. This is primarily used to maintain session when running long running commands from the CLI 
- The `RefreshSession` method and `LastSessionUpdateTime` only applies to IAM tokens.
1. Change directory to the root of the local repo 
2. Run the command: `go test -v -count=1 ./bluemix/authentication/iam`
3. Verify that all tests have passed
> feat(auth): Added LastSessionUpdateTime config

- i18n/i18n.go
- plugin_examples/list_plugin/commands/list_test.go
The purpose of this ticket to use the messageID as the translation if the translation cannot be found in the language files
> fix: Used messageID as translation if translation cannot be found

- .secrets.baseline
The purpose of this PR is to exclude the .nancy-ignore file from the security scan
> chore: Excluded .nancy-ignore in secrets.baseline file

- docs/plugin_developer_guide.md
The purpose of this PR is to provide clearly expectations to use a proper plugin name and alias when designing a plugin. It is important that plugin's names clearly describe what service the plugin is providing as well as short alias name for uninstall and installing the plugin.
> docs: Added details on plugin name and plugin alias standards in guide

- bluemix/configuration/persistor.go
- bluemix/version.go
> Fix: Excluding Windows `GOOS` from `flock` file mutex logic

- bluemix/configuration/config_helpers/helpers_test.go
- bluemix/env_test.go
```bash
allmi@SPF-WIN10 MINGW64 ~/go/src/github.com/IBM-Cloud/ibm-cloud-cli-sdk (dev)
$ go test github.com/IBM-Cloud/ibm-cloud-cli-sdk/bluemix/configuration/config_helpers
--- FAIL: TestConfigDir_NothingSet_NothingExists (0.00s)
helpers_test.go:56:
Error Trace:    helpers_test.go:56
Error:          Not equal:
expected: "C:\\Users\\allmi\\AppData\\Local\\Temp\\config_dir_test3369573905\\.bluemix"
actual  : "C:\\Users\\allmi\\.bluemix"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-C:\Users\allmi\AppData\Local\Temp\config_dir_test3369573905\.bluemix
+C:\Users\allmi\.bluemix
Test:           TestConfigDir_NothingSet_NothingExists
--- FAIL: TestConfigDir_NothingSet_IBMCloudExists (0.00s)
helpers_test.go:70:
Error Trace:    helpers_test.go:70
Error:          Not equal:
expected: …
```
> Win unit test

- common/rest/client.go
> fix: Adding a "Connection: Close" header in HTTP requests of our Go client

- bluemix/terminal/table.go
- bluemix/terminal/table_test.go
I would like to add a new format to represent the tables in `ibmcloud sl` where we use them a lot, print in csv format
Using the same format
```go
testTable := NewTable(&buf, []string{"col1", "col2"})
testTable.Add("row1-col1", "row1-col2")
testTable.Add("row2-col1", "row2-col2")
testTable.PrintCsv()
```
The output would look like this
```
col1,col2
row1-col1,row1-col2
row2-col1,row2-col2
```
> Adds PrintCsv() function and unit tests to bluemix/terminal/table

- bluemix/configuration/config_helpers/helpers.go
- bluemix/configuration/config_helpers/helpers_test.go
- common/rest/request_test.go
The purpose of this PR is to add a validation method to check if the next url contains the expected queries used during pagination. For instance, if the user is paginating with the `active` query parameter any cached url that is missing the `active` query parameter is invalid
1. Run the command: `go test -v -count=1 ./...`
2. Verify that all tests pass
> feat: added validation method for pagination cache url

- bluemix/configuration/core_config/bx_config.go
- bluemix/configuration/core_config/repository.go
- bluemix/crn/crn.go
The files changed here add a check to return an empty string (which will result in omission with the `omitempty` JSON-formatting tag), instead of `:::::::::`, if all of the 10 colon-delimited components of the CRN are empty.
Left behind last time but also necessary for the next merge/deploy (and therefore included here) are changes to the module for reading from and writing to the core configuration file, which we need in order to support assuming a TP on the CLI.
> feat: add crn check & feat: add assumed TP readers/modifiers

- bluemix/version.go
We're releasing a new version of the CLI SDK to be up-to-date with the latest changes on the IBM Cloud CLI.
> chore: change the minor version number

- bluemix/configuration/core_config/bx_config.go
- bluemix/configuration/core_config/repository.go
The purpose of this PR is to add a new configuration called `AlphaCommandsEnabled` which will handle sorting commands alphabetically uncategorized in the help usage text
> feat: added AlphaCommandsEnabled configuration

- bluemix/terminal/table.go
- bluemix/terminal/table_test.go
There is an issue with table rows wrapping causing problems for customers. It is possible it is due to how `term.GetSize` is determining the width size. Until the issue is resolved we will set the terminal width to a large amount to prevent wrapping
> chore: hardcoded terminal width to a large number

- go.mod
This PR updates the Golang version as was done in `master` previously.
> chore: bump golang to 1.22.11

- bluemix/version.go
New release that updates vulnerable dependency versions
> chore: bump version to 1.7.1

- plugin/plugin.go
- testhelpers/terminal/test_ui.go
The purpose of this PR is resolve the issue where only the local flags were included in a plug-in's metadata. There is a strange bug in Cobra where you need to call either `InheriteFlags()` or `LocalFlags()` in order to include global flags before visiting all the flags (see https://github.com/spf13/cobra/issues/412)
> fix: included all flags in metadata

- bluemix/env.go
- plugin/plugin.go
- plugin/plugin_context.go
The purpose of this PR is to add a new method called *MCPEnabled* in the **PluginContext** module which will allow users to determine whether or not the CLI is running as a MCP server
> feat: added method to check if CLI is in MCP mode

- bluemix/authentication/iam/iam.go
- bluemix/authentication/iam/iam_test.go
The purpose of this PR is to suppress printing the **Correlation IDs** on certain requests (eg. `/v1/sesssion`)
> chore: added check to not print correlation ID on certain reqs
